@startuml
class MaterialRepositoryTests {
    + MaterialRepositoryTests()
    + <<async>> CreateAsync_material_returns_new_material_with_id() : Task
    + <<async>> CreateAsync_material_returns_conflict_with_existing_id() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_too_long_title() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_tag_not_existing() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_wrong_tag_weight() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_too_long_tag_name() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_duplicate_tag() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_duplicate_media() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_media_not_existing() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_too_long_media_name() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_wrong_rating_weight() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_too_long_rating_name() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_duplicate_user_with_different_ratings() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_too_long_author_first_name() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_too_long_author_sur_name() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_duplicate_author() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_level_not_existing() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_too_long_level_name() : Task
    + <<async>> CreateAsync_material_returns_created_on_duplicate_level() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_language_not_existing() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_too_long_language_name() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_programming_language_not_existing() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_too_long_programming_language_name() : Task
    + <<async>> CreateAsync_material_returns_created_on_duplicate_programming_language() : Task
    + <<async>> CreateAsync_material_returns_bad_request_on_too_long_summary() : Task
    + <<async>> ReadAsync_material_by_id_returns_material_check_title_and_status_found() : Task
    + <<async>> ReadAsync_material_by_id_returns_empty_material_check_title_and_status_notFound() : Task
    + <<async>> ReadAsync_material_by_id_returns_material_check_tags_and_status_found() : Task
    + <<async>> ReadAsync_material_by_id_returns_material_check_ratings_and_status_found() : Task
    + <<async>> ReadAsync_material_by_id_returns_material_check_levels_and_status_found() : Task
    + <<async>> ReadAsync_material_by_id_returns_material_check_programming_language_and_status_found() : Task
    + <<async>> ReadAsync_material_by_id_returns_material_check_media_and_status_found() : Task
    + <<async>> ReadAsync_material_by_id_returns_material_check_authors_and_status_found() : Task
    + <<async>> ReadAsync_material_by_id_returns_material_check_language_and_status_found() : Task
    + <<async>> ReadAsync_material_by_id_returns_material_check_summary_and_status_found() : Task
    + <<async>> ReadAsync_material_by_id_returns_material_check_url_and_status_found() : Task
    + <<async>> ReadAsync_material_by_id_returns_material_check_content_and_status_found() : Task
    + <<async>> ReadAllAsync_returns_all_material_check_titles() : Task
    + <<async>> ReadAllAsync_returns_all_material_check_tags() : Task
    + <<async>> ReadAllAsync_returns_all_material_check_ratings() : Task
    + <<async>> ReadAllAsync_returns_all_material_check_levels() : Task
    + <<async>> ReadAllAsync_returns_all_material_check_authors() : Task
    + <<async>> ReadAllAsync_returns_all_material_check_programming_languages() : Task
    + <<async>> ReadAllAsync_returns_all_material_check_medias() : Task
    + <<async>> ReadAllAsync_returns_all_material_check_language() : Task
    + <<async>> ReadAllAsync_returns_all_material_check_summary() : Task
    + <<async>> ReadAllAsync_returns_all_material_check_url() : Task
    + <<async>> ReadAllAsync_returns_all_material_check_content() : Task
    + <<async>> ReadAsync_given_search_form_input_with_rating_above_average_of_10_should_return_material() : Task
    + <<async>> ReadAsync_given_search_material_form_input_with_rating_above_average_of_0_should_return_all_materials() : Task
    + <<async>> ReadAsync_given_search_material_form_input_with_rating_above_average_of_3_should_return_two_materials() : Task
    + <<async>> ReadAsync_given_programming_language_filter_c_sharp_should_only_return_materials_with_csharp() : Task
    + <<async>> ReadAsync_given_filter_than_doesnt_exist_return_no_materials() : Task
    + <<async>> DeleteAsync_material_by_id_returns_status_deleted() : Task
    + <<async>> DeleteAsync_material_by_id_returns_status_notFound() : Task
    + <<async>> DeleteAsync_material_by_id_returns_count_one_less() : Task
    + <<async>> UpdateAsync_material_by_id_returns_status_updated() : Task
    + <<async>> UpdateAsync_material_by_id_returns_new_title() : Task
    + <<async>> UpdateAsync_material_by_id_returns_material_returns_new_tags() : Task
    + <<async>> UpdateAsync_material_by_id_returns_material_returns_new_ratings() : Task
    + <<async>> UpdateAsync_material_by_id_returns_material_returns_new_levels() : Task
    + <<async>> UpdateAsync_material_by_id_returns_material_returns_new_programming_languages() : Task
    + <<async>> UpdateAsync_material_by_id_returns_material_returns_new_medias() : Task
    + <<async>> UpdateAsync_material_by_id_returns_new_language() : Task
    + <<async>> UpdateAsync_material_by_id_returns_new_content() : Task
    + <<async>> UpdateAsync_material_by_id_returns_new_summary() : Task
    + <<async>> UpdateAsync_material_by_id_returns_new_url() : Task
    + <<async>> UpdateAsync_material_by_id_returns_status_notFound() : Task
    + <<async>> UpdateAsync_material_by_id_returns_status_Conflict() : Task
    + <<async>> UpdateAsync_material_by_id_returns_status_BadRequest() : Task
    + <<async>> MayContainProgrammingLanguage_given_materials_with_c_sharp_pl_should_find_materials() : Task
    + <<async>> MayContainProgrammingLanguage_given_materials_with_no_pls_should_find_materials() : Task
    + <<async>> MayContainProgrammingLanguage_given_search_input_with_programming_language_clojure_should_not_find_materials() : Task
    + <<async>> MayContainLanguage_given_material_with_language_danish_should_find_material() : Task
    + <<async>> MayContainLanguage_given_material_with_no_language_given_should_find_materials() : Task
    + <<async>> MayContainLanguage_given_material_with_language_volapük_should_not_find_material() : Task
    + <<async>> MayContainMedia_search_with_no_given_media_should_find_material() : Task
    + <<async>> MayContainMedia_search_with_media_book_should_return_1_material() : Task
    + <<async>> MayContainMedia_search_with_media_mysterious_format_should_return_no_materials() : Task
    + <<async>> MayContainTag_search_with_no_tags_should_return_all_materials() : Task
    + <<async>> MayContainTag_search_with_tag_solid_should_return_1_element() : Task
    + <<async>> MayContainTag_search_with_tag_mystery_tag_should_return_no_element() : Task
    + <<async>> MayContainLevel_search_with_no_level_returns_all_materials() : Task
    + <<async>> MayContainLevel_search_with_level_phd_returns_1_materials() : Task
    + <<async>> MayContainLevel_search_with_level_mysterious_degree_should_return_no_materials() : Task
}
@enduml
