@startuml
class ErrorModel {
    + ErrorModel(logger:ILogger<ErrorModel>)
    + RequestId : string? <<get>>
    + ShowRequestId : bool <<get>>
    + OnGet() : void
}
PageModel <|-- ErrorModel
@enduml
