@startuml
!include .\\WebService.Core.Client.Tests\IndexTest.puml
!include .\\WebService.Core.Server.Tests\GlobalUsing.puml
!include .\\WebService.Core.Shared.Tests\MaterialDTOTests.puml
!include .\\WebService.Entities\Author.puml
!include .\\WebService.Entities\Context.puml
!include .\\WebService.Entities\GlobalUsing.puml
!include .\\WebService.Entities\IContext.puml
!include .\\WebService.Entities\Language.puml
!include .\\WebService.Entities\Level.puml
!include .\\WebService.Entities\Material.puml
!include .\\WebService.Entities\Media.puml
!include .\\WebService.Entities\ProgrammingLanguage.puml
!include .\\WebService.Entities\Rating.puml
!include .\\WebService.Entities\Tag.puml
!include .\\WebService.Infrastructure\Extensions.puml
!include .\\WebService.Infrastructure\GlobalUsing.puml
!include .\\WebService.Infrastructure\LanguageRepository.puml
!include .\\WebService.Infrastructure\LevelRepository.puml
!include .\\WebService.Infrastructure\MaterialRepository.puml
!include .\\WebService.Infrastructure\MediaRepository.puml
!include .\\WebService.Infrastructure\ProgrammingLanguageRepository.puml
!include .\\WebService.Infrastructure\SearchAlgorithm.puml
!include .\\WebService.Infrastructure\TagRepository.puml
!include .\\WebService.Infrastructure.Tests\GlobalUsing.puml
!include .\\WebService.Core\Client\Program.puml
!include .\\WebService.Core\Server\GlobalUsing.puml
!include .\\WebService.Core\Server\Program.puml
!include .\\WebService.Core\Shared\AuthorDTO.puml
!include .\\WebService.Core\Shared\GlobalUsing.puml
!include .\\WebService.Core\Shared\ILanguageRepository.puml
!include .\\WebService.Core\Shared\ILevelRepository.puml
!include .\\WebService.Core\Shared\IMaterialRepository.puml
!include .\\WebService.Core\Shared\IMediaRepository.puml
!include .\\WebService.Core\Shared\IProgrammingLanguageRepository.puml
!include .\\WebService.Core\Shared\IRepository.puml
!include .\\WebService.Core\Shared\ISearch.puml
!include .\\WebService.Core\Shared\ITagRepository.puml
!include .\\WebService.Core\Shared\LanguageDTO.puml
!include .\\WebService.Core\Shared\LevelDTO.puml
!include .\\WebService.Core\Shared\MaterialDTO.puml
!include .\\WebService.Core\Shared\MediaDTO.puml
!include .\\WebService.Core\Shared\ProgrammingLanguageDTO.puml
!include .\\WebService.Core\Shared\RatingDTO.puml
!include .\\WebService.Core\Shared\SearchForm.puml
!include .\\WebService.Core\Shared\Status.puml
!include .\\WebService.Core\Shared\TagDTO.puml
!include .\\WebService.Core.Server.Tests\ControllerTests\LanguageControllerTests.puml
!include .\\WebService.Core.Server.Tests\ControllerTests\LevelControllerTests.puml
!include .\\WebService.Core.Server.Tests\ControllerTests\MaterialControllerTests.puml
!include .\\WebService.Core.Server.Tests\ControllerTests\MediaControllerTests.puml
!include .\\WebService.Core.Server.Tests\ControllerTests\ProgrammingLanguageControllerTests.puml
!include .\\WebService.Core.Server.Tests\ControllerTests\SearchControllerTests.puml
!include .\\WebService.Core.Server.Tests\ControllerTests\TagControllerTests.puml
!include .\\WebService.Core.Server.Tests\ControllerTests\TestVariables.puml
!include .\\WebService.Core.Server.Tests\ModelTests\ContentGeneratorTests.puml
!include .\\WebService.Entities\Migrations\20211210091309_init.puml
!include .\\WebService.Entities\Migrations\20211210091309_init.Designer.puml
!include .\\WebService.Entities\Migrations\20211210091654_add_material_to_language_relation.puml
!include .\\WebService.Entities\Migrations\20211210091654_add_material_to_language_relation.Designer.puml
!include .\\WebService.Entities\Migrations\ContextModelSnapshot.puml
!include .\\WebService.Infrastructure.Tests\ContextRepositoryTests\LanguageRepositoryTests.puml
!include .\\WebService.Infrastructure.Tests\ContextRepositoryTests\LevelRepositoryTests.puml
!include .\\WebService.Infrastructure.Tests\ContextRepositoryTests\MaterialRepositoryTests.puml
!include .\\WebService.Infrastructure.Tests\ContextRepositoryTests\MediaRepositoryTests.puml
!include .\\WebService.Infrastructure.Tests\ContextRepositoryTests\ProgrammingLanguageRepositoryTests.puml
!include .\\WebService.Infrastructure.Tests\ContextRepositoryTests\TagRepositoryTests.puml
!include .\\WebService.Infrastructure.Tests\ContextRepositoryTests\TestVariables.puml
!include .\\WebService.Infrastructure.Tests\SearchAlgorithmTests\SearchAlgorithmTest.puml
!include .\\WebService.Infrastructure.Tests\SearchAlgorithmTests\SearchTestVariables.puml
!include .\\WebService.Core\Server\Controllers\LanguageController.puml
!include .\\WebService.Core\Server\Controllers\LevelController.puml
!include .\\WebService.Core\Server\Controllers\MaterialController.puml
!include .\\WebService.Core\Server\Controllers\MediaController.puml
!include .\\WebService.Core\Server\Controllers\ProgrammingLanguageController.puml
!include .\\WebService.Core\Server\Controllers\SearchController.puml
!include .\\WebService.Core\Server\Controllers\TagController.puml
!include .\\WebService.Core\Server\Model\ContentGenerator.puml
!include .\\WebService.Core\Server\Model\SeedExtensions.puml
!include .\\WebService.Core\Server\Pages\Error.cshtml.puml
!include .\\WebService.Core.Client.Tests\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Core.Client.Tests\obj\Debug\net6.0\WebService.Core.Client.Tests.AssemblyInfo.puml
!include .\\WebService.Core.Client.Tests\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Core.Client.Tests\obj\Release\net6.0\WebService.Core.Client.Tests.AssemblyInfo.puml
!include .\\WebService.Core.Server.Tests\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Core.Server.Tests\obj\Debug\net6.0\WebService - Backup.Core.Server.Tests.AssemblyInfo.puml
!include .\\WebService.Core.Server.Tests\obj\Debug\net6.0\WebService.Core.Server.Tests.AssemblyInfo.puml
!include .\\WebService.Core.Server.Tests\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Core.Server.Tests\obj\Release\net6.0\WebService - Backup.Core.Server.Tests.AssemblyInfo.puml
!include .\\WebService.Core.Server.Tests\obj\Release\net6.0\WebService.Core.Server.Tests.AssemblyInfo.puml
!include .\\WebService.Core.Shared.Tests\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Core.Shared.Tests\obj\Debug\net6.0\WebService.Core.Shared.Tests.AssemblyInfo.puml
!include .\\WebService.Core.Shared.Tests\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Core.Shared.Tests\obj\Release\net6.0\WebService.Core.Shared.Tests.AssemblyInfo.puml
!include .\\WebService.Entities\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Entities\obj\Debug\net6.0\WebService.Entities.AssemblyInfo.puml
!include .\\WebService.Entities\obj\Debug\net6.0\WebService.Entities.GlobalUsings.g.puml
!include .\\WebService.Entities\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Entities\obj\Release\net6.0\WebService.Entities.AssemblyInfo.puml
!include .\\WebService.Entities\obj\Release\net6.0\WebService.Entities.GlobalUsings.g.puml
!include .\\WebService.Infrastructure\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Infrastructure\obj\Debug\net6.0\WebService.Infrastructure.AssemblyInfo.puml
!include .\\WebService.Infrastructure\obj\Debug\net6.0\WebService.Infrastructure.GlobalUsings.g.puml
!include .\\WebService.Infrastructure\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Infrastructure\obj\Release\net6.0\WebService.Infrastructure.AssemblyInfo.puml
!include .\\WebService.Infrastructure\obj\Release\net6.0\WebService.Infrastructure.GlobalUsings.g.puml
!include .\\WebService.Infrastructure.Tests\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Infrastructure.Tests\obj\Debug\net6.0\WebService.Infrastructure.Tests.AssemblyInfo.puml
!include .\\WebService.Infrastructure.Tests\obj\Debug\net6.0\WebService.Infrastructure.Tests.GlobalUsings.g.puml
!include .\\WebService.Infrastructure.Tests\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Infrastructure.Tests\obj\Release\net6.0\WebService.Infrastructure.Tests.AssemblyInfo.puml
!include .\\WebService.Infrastructure.Tests\obj\Release\net6.0\WebService.Infrastructure.Tests.GlobalUsings.g.puml
!include .\\WebService.Core\Client\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Core\Client\obj\Debug\net6.0\WebService.Core.Client.AssemblyInfo.puml
!include .\\WebService.Core\Client\obj\Debug\net6.0\WebService.Core.Client.GlobalUsings.g.puml
!include .\\WebService.Core\Client\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Core\Client\obj\Release\net6.0\WebService.Core.Client.AssemblyInfo.puml
!include .\\WebService.Core\Client\obj\Release\net6.0\WebService.Core.Client.GlobalUsings.g.puml
!include .\\WebService.Core\Server\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Core\Server\obj\Debug\net6.0\WebService.Core.Server.AssemblyInfo.puml
!include .\\WebService.Core\Server\obj\Debug\net6.0\WebService.Core.Server.GlobalUsings.g.puml
!include .\\WebService.Core\Server\obj\Debug\net6.0\WebService.Core.Server.MvcApplicationPartsAssemblyInfo.puml
!include .\\WebService.Core\Server\obj\Debug\net6.0\WebService.Core.Server.RazorAssemblyInfo.puml
!include .\\WebService.Core\Server\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Core\Server\obj\Release\net6.0\WebService.Core.Server.AssemblyInfo.puml
!include .\\WebService.Core\Server\obj\Release\net6.0\WebService.Core.Server.GlobalUsings.g.puml
!include .\\WebService.Core\Server\obj\Release\net6.0\WebService.Core.Server.RazorAssemblyInfo.puml
!include .\\WebService.Core\Shared\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Core\Shared\obj\Debug\net6.0\WebService.Core.Shared.AssemblyInfo.puml
!include .\\WebService.Core\Shared\obj\Debug\net6.0\WebService.Core.Shared.GlobalUsings.g.puml
!include .\\WebService.Core\Shared\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\WebService.Core\Shared\obj\Release\net6.0\WebService.Core.Shared.AssemblyInfo.puml
!include .\\WebService.Core\Shared\obj\Release\net6.0\WebService.Core.Shared.GlobalUsings.g.puml
@enduml
