@startuml
!theme plain

database "Database" as DB
component API {
    component LoginController
}
component Search {
    component SearchAlgorithm
}
cloud Authentication
component FrontEnd

FrontEnd -u-> API
API -d--> Search : <<with searchForm>>

LoginController <..> Authentication
Authentication --> FrontEnd

API -d-> DB



@enduml