@startuml
!theme plain
left to right direction
package WebService.Entities {
    !include .\Author.puml
    !include .\Context.puml
    !include .\IContext.puml
    !include .\Language.puml
    !include .\Level.puml
    !include .\Material.puml
    !include .\Media.puml
    !include .\ProgrammingLanguage.puml
    !include .\Rating.puml
    !include .\Tag.puml
}

@enduml