@startuml
!theme plain
interface ILevelRepository {
    CreateAsync(level:CreateLevelDTO) : Task<(Status, LevelDTO)>
    ReadAsync(levelId:int) : Task<(Status, LevelDTO)>
    ReadAsync() : Task<IReadOnlyCollection<LevelDTO>>
    DeleteAsync(levelId:int) : Task<Status>
    UpdateAsync(levelDTO:LevelDTO) : Task<Status>
}
IRepository <|-- ILevelRepository
Status <-- ILevelRepository
@enduml
