@startuml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\Author.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\AuthorDTO.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\ContentGenerator.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\Context.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\Extensions.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\GlobalUsing.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\IContext.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\ILanguageRepository.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\ILevelRepository.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\IMaterialRepository.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\IMediaRepository.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\include.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\IProgrammingLanguageRepository.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\IRepository.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\ISearch.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\ITagRepository.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\Language.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\LanguageController.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\LanguageDTO.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\LanguageRepository.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\Level.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\LevelController.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\LevelDTO.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\LevelRepository.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\Material.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\MaterialController.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\MaterialDTO.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\MaterialRepository.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\Media.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\MediaController.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\MediaDTO.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\MediaRepository.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\Program.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\ProgrammingLanguage.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\ProgrammingLanguageController.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\ProgrammingLanguageDTO.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\ProgrammingLanguageRepository.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\Rating.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\RatingDTO.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\SearchAlgorithm.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\SearchController.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\SearchForm.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\SeedExtensions.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\Status.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\Tag.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\TagController.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\TagDTO.puml
!include C:\Users\andre\Source\School\BDSA2021-FinalProject\Documentation\UML\CollectedPumls\TagRepository.puml
@enduml
