@startuml
!theme plain
left to right direction
package WebService.Infrastructure  {
    class LanguageRepository
    class LevelRepository
    class MaterialRepository
    class MediaRepository
    class ProgrammingLanguageRepository
    class SearchAlgorithm
    class TagRepository
}

@enduml