@startuml
!theme plain
class CreateLevelDTO {
+ CreateLevelDTO(name:string)
+ Name : string <<get>>
}
class LevelDTO {
+ LevelDTO(id:int, name:string)
+ Id : int <<get>>
}

CreateLevelDTO <|-- LevelDTO
@enduml
