@startuml
!theme plain
class CreateProgrammingLanguageDTO {
+ CreateProgrammingLanguageDTO(name:string)
+ Name : string <<get>>
}
class ProgrammingLanguageDTO {
+ ProgrammingLanguageDTO(id:int, name:string)
+ Id : int <<get>>
}

CreateProgrammingLanguageDTO <|-- ProgrammingLanguageDTO
@enduml
