@startuml
!theme plain
package WebService.Core.Server {
    package WebService.Core.Server.Controllers {
        class LanguageController
        class LevelController
        class MaterialController
        class MediaController
        class ProgrammingLanguageController
        class SearchController
        class TagController
    }

    package WebService.Core.Server.Model {
        class ContentGenerator
        class SeedExtensions
    }

    class Program { }
}

ContentGenerator <-o SeedExtensions


@enduml