@startuml
class MaterialDTOTests {
    + MaterialDTOTests()
    + ConvertToMaterialDTOReturnsIdenticalMaterialDTO() : void
    + AverageRatingReturns7_8() : void
    + LevelsToStringReturnsLevelNamesSeperatedBySpaces() : void
    + AuthorsToStringReturnFullNamesSeperatedByComma() : void
}
@enduml
