@startuml
class SearchController {
    + SearchController(search:ISearch)
    + <<async>> Post(searchForm:SearchForm) : Task<ActionResult<ICollection<MaterialDTO>>>
}
ControllerBase <|-- SearchController
@enduml
