@startuml
class LanguageControllerTests {
    + LanguageControllerTests()
    + <<async>> Post_language_returns_status_created() : Task
    + <<async>> Post_language_returns_status_conflict() : Task
    + <<async>> Post_language_returns_status_badRequest() : Task
    + <<async>> Get_all_languages_returns_status_ok() : Task
    + <<async>> Get_language_returns_status_ok() : Task
    + <<async>> Get_language_returns_status_notFound() : Task
    + <<async>> Delete_language_returns_status_noContent() : Task
    + <<async>> Delete_language_returns_status_notFound() : Task
    + <<async>> Put_language_returns_status_noContent() : Task
    + <<async>> Put_language_returns_status_conflict() : Task
    + <<async>> Put_language_returns_status_badRequest() : Task
    + <<async>> Put_language_returns_status_notFound() : Task
}
@enduml
